fos_rest:
  exception:
    enabled: true
    exception_controller: 'fos_rest.exception.twig_controller:showAction'
    codes:
      App\Exception\ModelValidationException: HTTP_BAD_REQUEST
      App\Exception\CommentNotFoundException: HTTP_NOT_FOUND

  param_fetcher_listener:  true
  allowed_methods_listener:  true
  routing_loader: true

  view:
    view_response_listener:  true

  format_listener:
    rules:
      - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }

  body_converter:
    enabled: true
    validate: true
    validation_errors_argument: validationErrors

  body_listener:
    array_normalizer: fos_rest.normalizer.camel_keys
